# Date: September 2017
# Author: Kutay B. Sezginel
"""
Initialize thermal conductivity calculation in Lammps
"""
from thermof.initialize import read_lines, write_lines
from thermof.sample import thermal_conductivity_file


def get_tc_lines(parameters, tc_file=thermal_conductivity_file):
    """
    Get thermal conductivity calculation Lammps input lines

    Args:
        - parameters (Parameters): Lammps parameters (see thermof.parameters)
        - tc_file (str): Sample thermal conductivity Lammps input file

    Returns:
        - list: List of Lammps input lines for thermal conductivity calculations
    """
    tc_lines = read_lines(tc_file)
    tc_lines[1] = 'variable        T equal %.1f\n' % parameters.temp
    tc_lines[2] = 'variable        dt equal %.1f\n' % parameters.timestep
    tc_lines[3] = 'variable        seed equal %i\n' % parameters.seed
    return tc_lines


def add_thermal_conductivity(inp_file, parameters, tc_file=thermal_conductivity_file):
    """
    Add thermal conductivity calculation to Lammps input file

    Args:
        - inp_file (str): Lammps input file generated by lammps_interface (will be overwritten)
        - parameters (Parameters): Lammps parameters (see thermof.parameters)
        - tc_file (str): Sample thermal conductivity Lammps input file

    Returns:
        - None: Overwrites given Lammps input file
    """
    inp_lines = read_lines(inp_file)
    tc_lines = get_tc_lines(parameters, tc_file=tc_file)
    inp_lines += tc_lines
    write_lines(inp_file, inp_lines)
